/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/socket`; params?: Router.UnknownInputParams; } | { pathname: `/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/styles/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[uuid]`, params: Router.UnknownInputParams & { uuid: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/config`; params?: Router.UnknownOutputParams; } | { pathname: `/inbox`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/socket`; params?: Router.UnknownOutputParams; } | { pathname: `/UserContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[uuid]`, params: Router.UnknownOutputParams & { uuid: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/config${`?${string}` | `#${string}` | ''}` | `/inbox${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/socket${`?${string}` | `#${string}` | ''}` | `/UserContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/styles/Colors${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/config`; params?: Router.UnknownInputParams; } | { pathname: `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/socket`; params?: Router.UnknownInputParams; } | { pathname: `/UserContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/styles/Colors`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[uuid]`, params: Router.UnknownInputParams & { uuid: string | number; } };
    }
  }
}
